### ISSUE TITLE
artist_select solution is wrong?

### ISSUE THREAD

**Issue by aparkening** [learn-co-curriculum/modification-nested-routes-lab#11]
The current solution for displaying `artist_select` **always** displays a dropdown if the song has an artist, regardless of whether you're editing from http://localhost:3000/artists/1/songs/1/edit or http://localhost:3000/songs/1/edit. From the instructions below, aren't we supposed to display a dropdown **only** if we're directly editing http://localhost:3000/songs/1/edit?

Instead of sending `artist_select` a redundant `artist` parameter (which we already have inside `song`), shouldn't the second parameter be some sort of path variable, since we care about how the user is reaching the form? That way we could display name only if artist exists && we're at the correct path.

**Original instructions:**
> Create a helper to display a drop-down list of artists if someone edits a song directly via /songs/id/edit and to only display the artist's name if they are editing through nested routing. Name the helper method artist_select. Hint: You'll need to set a variable in the controller action to pass to the helper method as an argument along with a song instance.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue is resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
