### ISSUE TITLE
 artists_helper_spec.rb:15 requires 2 arguments when only 1 is needed

### ISSUE THREAD

**Issue by hansenjl** [learn-co-curriculum/modification-nested-routes-lab#6]
There is a specific test in the  artists_helper_spec.rb file that requires two arguments to be passed in (song and artist). It seems unnecessary because it is possible to pall all other test by only passing in the song as an argument since `song.artist` can be used in place of `artist`. It seems odd to require 2 arguments if there is a way to code this method with only one.

**Comment by kwebster2** [comment]
@weezwo ^

**Comment by maxwellbenton** [comment]
Hi @hansenjl,

Thank you for providing this feedback. We are in the process of rewriting this section of the course and will be updating the tests in this lesson.

As always, thank you for your contributions!
