### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by maxwellbenton** [learn-co-curriculum/modification-nested-routes-lab#8]
Problem: Tests need to be filled out, fixed:

"There is a specific test in the artists_helper_spec.rb file that requires two arguments to be passed in (song and artist). It seems unnecessary because it is possible to pall all other test by only passing in the song as an argument since song.artist can be used in place of artist. It seems odd to require 2 arguments if there is a way to code this method with only one."

"The tests in this lab need to be filled out some. Specifically the artists_helper_spec and features/songs_spec"

**Comment by AspenJames** [comment]
+1 - The README and specs are very vague and unclear on what the expectation is here.

The only spec checks number of arguments, and there is almost no way to figure out what is expected save for checking the solution branch. 

Recommend clarifying README + specs, or removing that spec entirely, allowing students to use one argument as suggested above

**Comment by drakeltheryuujin** [comment]
We have updated the materials to not include that test so this should be resolved.
