### ISSUE TITLE
Colors missing on many of the tests in Rails section lab

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/modification-nested-routes-lab#9]
It's tough to tell which tests you've passed when they are all in white type, not green for passing and red for failing.

One solution is to create .rspec file in the lab directory and put this in it:
--color
--format documentation
--require spec_helper

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
The materials were updated with commit 321d190 and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
